### ISSUE TITLE
[Widget] Top Sales Orders

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-hestia-dashboard#8]
Add widget in the Dashboard that shows the top sales orders similar to this:

![image](https://github.com/codbex/codbex-hestia/assets/5245055/c54d4567-8e66-4f4b-adea-a8587ba993d7)

**Comment by MinaDoncheva** [comment]
fixed with commit https://github.com/codbex/codbex-hestia/commit/23cdd172c560799c5d982bc15b03e8b913417068

**Comment by MinaDoncheva** [comment]
fixed with commit https://github.com/codbex/codbex-hestia/commit/23cdd172c560799c5d982bc15b03e8b913417068
