### ISSUE TITLE
[Widget] Top Customer

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-hestia-dashboard#9]
Add widget in the Dashboard that shows the top customers similar to this: 

![image](https://github.com/codbex/codbex-hestia/assets/5245055/aa4ac1ba-f88d-4583-8d46-5f5acb8d9dd7)

**Comment by MinaDoncheva** [comment]
fixed with https://github.com/codbex/codbex-hestia/pull/25/commits/9b74331f7528a06b8bd93a14b2b9046f1689daba and https://github.com/codbex/codbex-hestia/commit/fa6e08845d750ea5a3bc67cd74a0d63a7f480363
